pipeline {
  agent any
  

  stages {
    stage ("Checkout") {
      steps {
        checkout scm
      }
    }

    stage ("Pushing Docker Image") {
      steps {
        script {
          docker.withRegistry('https://index.docker.io/v1/', 'dockerhubcred') {
            def app = docker.build("rameshthangaraj/mypythonimage", "./dockerapps")
            app.push()
          }
        }
      }
    }
    
       stage ("Pulling Docker Image and testing inside it") {
         when {
                branch 'main'
            }
      steps {
        script {
          docker.withRegistry('https://index.docker.io/v1/', 'dockerhubcred') {
            def app = docker.build("rameshthangaraj/mypythonimage", "./dockerapps")
            app.pull()
            app.inside() {
              sh 'ls'
}
          }
        }
      }
    }

    stage ("Deploy in AKS cluster") {
      steps {
        script {
          env.PIPELINE_NAMESPACE = "kube-system"
          kubernetesDeploy kubeconfigId: 'sandboxtestcluster', configs: 'dockerapps/deployment.yaml'
          kubernetesDeploy kubeconfigId: 'sandboxtestcluster', configs: 'dockerapps/service.yaml'
        }
      }
    }
  }
  post {
  success {
    echo "Running ${env.JOB_NAME} ${env.BUILD_ID} on ${env.JENKINS_URL} ${env.NODE_NAME}"
  print 'Job completed successfully.'

}
  }


}
