pipeline {
  agent (any) 
  environment {
    name = abc
    loc = dba

  }

  stages {
    stage ("Checkout") {
      steps {
        checkout scm 

      }
	  }
	  
	  stage ("Pushing the docker Image") {
      steps {
        docker.withRegistry('https://dockerhub.io/rameshthangaraj', 'dockerhubcreds') {
          def app = docker.build("pytest-image:${env.BUILD_ID}", "./example2/Dockerfile")
          app.push()

        }
        
      }
    }

}

}
