pipeline {
  agent (any)
  environment {
    name = "abc"
    loc = "dba"

  }

  stages {
    stage ("Checkout") {
      steps {
        checkout scm

      }
	  }

	  stage ("Pushing the docker Image") {
      steps {

	      script{

          docker.withRegistry('https://index.docker.io/v1/', 'dockerhubcred') {

            def app = docker.build("rameshthangaraj/pytest-image", "./example2/")
            app.push()

        }
        }
      }
    }

    stage ("Deploy in AKS cluster") {
      steps {
        script {
          env.PIPELINE_NAMESPACE = "kube-system"
          kubernetesDeploy kubeconfigId: 'sandboxtestcluster', configs: 'example2/nginx-deploy.yaml'
	  kubernetesDeploy kubeconfigId: 'sandboxtestcluster', configs: 'example2/deployment.yaml'
        }
      }
    }

}
}

