node {
  def app
  step('Clone repo') {
    checkout scm
  }
  step('Build Image') {
    app = docker.build("rameshthangaraj/hello")

  }
  step('Test') {
    app.inside {
      sh 'echo "Test passed"'


    }

  }
  step('Push Image') {
    docker.withRegistry('https://registry.hub.docker.com', 'git') {
       app.push("${env.BUILD_NUMBER}")
       app.push("latest")
    }
  }
  stage('Delpoying the App on Azure Kubernetes Service') {
    app = docker.image('testacr.azurecr.io/demo:latest')
    withDockerRegistry([credentialsId: 'acr_credentials', url: 'https://testacr.azurecr.io']) {
    app.pull()
    sh "kubectl create -f ."
    }
   }
}



