pipeline {
    agent {
    docker {
        image 'maven:3-alpine'
	

      }
   }
    options {
        skipDefaultCheckout true
        buildDiscarder(logRotator(numToKeepStr:'10'))
    }
	 stages {
	 
        stage('checkout-repo') {
            steps {
              checkout scm
            }
        }

		stage('Maven-build'){
		    steps {
            sh " ls -lrt /var/lib/jenkins/workspace/mavendocker;ls -lrt /var/lib/jenkins/workspace/mavendocker@tmp;mvn -Dmaven.test.failure.ignore=true clean package"
            }		 
		
		}
		

	}
  post {
            always {
                echo "Post deployment completed"
				//cleanWs()
            }
    }
}
